"""The Odoo pipeline as data: addons + dependencies -> manifest + Dockerfile.

The customer's pipeline repo (from adomi-io/odoo-boilerplate) builds their Odoo
image. What used to be hand-written Dockerfile surgery — clone an OCA repo, copy
addon directories into extra_addons, pip/apt install — becomes a declarative
manifest (``adomi-pipeline.yaml``) the portal owns, plus a Dockerfile generated
from it. Both files are committed to the repo; the manifest is the source of
truth (hand edits there are imported back into the portal), the Dockerfile is a
build artifact.

Pure functions, no Odoo imports — unit-tested without a database.
"""

import yaml

MANIFEST_PATH = "adomi-pipeline.yaml"
DOCKERFILE_PATH = "Dockerfile"
DEFAULT_BASE_IMAGE = "ghcr.io/adomi-io/odoo:19.0"

MANIFEST_HEADER = """\
# Managed by the Adomi platform (the application's Pipeline tab).
# You can edit this file by hand — the portal imports your changes — but the
# Dockerfile is regenerated from it, so edit THIS file, not the Dockerfile.
"""

DOCKERFILE_HEADER = """\
# Generated by the Adomi platform from adomi-pipeline.yaml.
# Do not edit by hand: change adomi-pipeline.yaml (or the Pipeline tab in the
# portal) and this file is regenerated on the next commit.
"""


def _stage_name(repo_url, index):
    """A readable, unique Dockerfile stage name for an addon source."""
    tail = repo_url.rstrip("/").rsplit("/", 1)[-1]
    if tail.endswith(".git"):
        tail = tail[:-4]
    slug = "".join(c if c.isalnum() else "_" for c in tail.lower()).strip("_") or "src"
    return "addons_%d_%s" % (index, slug)


def render_manifest(data):
    """The adomi-pipeline.yaml text for a pipeline dict."""
    doc = {
        "odooBaseImage": data.get("base_image") or DEFAULT_BASE_IMAGE,
        "apt": list(data.get("apt") or []),
        "pip": list(data.get("pip") or []),
        "addons": [
            {
                "repo": s["repo"],
                "branch": s.get("branch") or "",
                "modules": list(s.get("modules") or []),
            }
            for s in data.get("addons") or []
        ],
    }
    return MANIFEST_HEADER + yaml.safe_dump(doc, default_flow_style=False, sort_keys=False)


def parse_manifest(text):
    """The pipeline dict for a manifest text (tolerates missing keys)."""
    doc = yaml.safe_load(text or "") or {}
    return {
        "base_image": doc.get("odooBaseImage") or "",
        "apt": [str(p) for p in doc.get("apt") or []],
        "pip": [str(p) for p in doc.get("pip") or []],
        "addons": [
            {
                "repo": str(s.get("repo") or ""),
                "branch": str(s.get("branch") or ""),
                "modules": [str(m) for m in s.get("modules") or []],
            }
            for s in doc.get("addons") or []
            if s and s.get("repo")
        ],
    }


def render_dockerfile(data):
    """A boilerplate-compatible Dockerfile for a pipeline dict.

    Mirrors adomi-io/odoo-boilerplate: one alpine stage per addon source clones
    the repo and copies the requested modules (every addon in the repo when the
    list is empty) into /tmp/extra_addons; the final image layers apt + pip
    dependencies onto the base, then copies config, the repo's own addons and
    every staged extra addon into /volumes.
    """
    base_image = data.get("base_image") or DEFAULT_BASE_IMAGE
    apt = list(data.get("apt") or [])
    pip = list(data.get("pip") or [])
    sources = list(data.get("addons") or [])

    lines = [DOCKERFILE_HEADER]
    lines.append("ARG ODOO_BASE_IMAGE=%s" % base_image)
    lines.append("")

    stages = []
    if sources:
        lines += [
            "FROM alpine:3.20 AS addons_base",
            "",
            "RUN apk add --no-cache git \\",
            "    && mkdir -p /tmp/extra_addons",
            "",
        ]
        for index, source in enumerate(sources):
            stage = _stage_name(source["repo"], index)
            stages.append(stage)
            branch = source.get("branch") or ""
            clone = "RUN git clone --depth 1 %s%s /tmp/src \\" % (
                ("--branch %s " % branch) if branch else "",
                source["repo"],
            )
            lines += ["FROM addons_base AS %s" % stage, "", clone]
            modules = source.get("modules") or []
            if modules:
                for module in modules:
                    lines.append("    && cp -a /tmp/src/%s /tmp/extra_addons/ \\" % module)
                lines[-1] = lines[-1].rstrip(" \\")
            else:
                # No explicit list: take every addon the repo ships.
                lines.append(
                    '    && for m in /tmp/src/*/__manifest__.py; do cp -a "$(dirname "$m")" /tmp/extra_addons/; done'
                )
            lines.append("")

    lines += ["FROM ${ODOO_BASE_IMAGE} AS configuration_layer", "", "USER root", ""]
    if apt:
        lines += [
            "RUN apt-get update \\",
            "    && apt-get install -y --no-install-recommends \\",
        ]
        lines += ["        %s \\" % p for p in apt]
        lines += ["    && rm -rf /var/lib/apt/lists/*", ""]
    if pip:
        lines.append("RUN pip install \\")
        lines += ["        %s \\" % p for p in pip]
        lines[-1] = lines[-1].rstrip(" \\")
        lines.append("")

    lines += [
        "FROM configuration_layer",
        "",
        "USER ubuntu",
        "",
        "WORKDIR /volumes",
        "",
        "COPY config/odoo.conf /volumes/config/odoo.conf",
        "",
        "COPY extra_addons /volumes/extra_addons",
    ]
    for stage in stages:
        lines.append("COPY --from=%s /tmp/extra_addons/ /volumes/extra_addons/" % stage)
    lines += ["", "COPY addons /volumes/addons", ""]

    return "\n".join(lines)
