[options]
# Database related options
db_user = $ODOO_DB_USER
db_password = $ODOO_DB_PASSWORD
db_host = $ODOO_DB_HOST
db_name = $ODOO_DB_NAME
db_port = $ODOO_DB_PORT
; db_sslmode = $ODOO_DB_SSLMODE
; db_maxconn = $ODOO_DB_MAXCONN

# Common options
server_wide_modules = $ODOO_SERVER_WIDE_MODULES
data_dir = $ODOO_DATA_DIR
addons_path = $ODOO_ADDONS_PATH
without_demo = $ODOO_WITHOUT_DEMO
; init = $ODOO_INIT
; update = $ODOO_UPDATE

# HTTP Service Configuration
proxy_mode = $ODOO_PROXY_MODE
; http_port = $ODOO_HTTP_PORT
; gevent_port = $ODOO_GEVENT_PORT

# Web interface Configuration
; dbfilter = $ODOO_DBFILTER

# Logging Configuration
; log_level = $ODOO_LOG_LEVEL

# Security-related options
; list_db = $ODOO_LIST_DB

# Multiprocessing options (POSIX only)
workers = $ODOO_WORKERS
limit_memory_soft = $ODOO_LIMIT_MEMORY_SOFT
limit_memory_hard = $ODOO_LIMIT_MEMORY_HARD
limit_time_cpu = $ODOO_LIMIT_TIME_CPU
limit_time_real = $ODOO_LIMIT_TIME_REAL
