{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adomi-platform-api.serviceAccountName" . }}
  labels:
    {{- include "adomi-platform-api.labels" . | nindent 4 }}
{{- end }}
